### ISSUE TITLE
Can't find math-content.css

### ISSUE THREAD

**Issue by drewyoungren** [rbeezer/sla#1]
When opening `RREF.sagews`, I get an IOError for the style sheets. I can fix it by altering the path to 
```
load("../../css/mathbook-content.css")
load("../../css/mathbook-add-on.css")
```

Is there a better way?

**Comment by rbeezer** [comment]
Dear Drew,

Yes, this is an expected problem.

Without internet access on an SMC project, we can't get the CSS off the AIM 
server for just any old SMC user.   Also, we need a slightly stripped-down 
version (div.mathbook-content) so some of the UI stuff does not overwrite some 
SMC styling of their UI.  So the best solution in my eyes is:

(a) David scripts the production of "mathbook-content.css" so it sees any fixes 
regularly.

(b) SMC whitelists aimath.org, or some subdirectory of it.

Not sure if this is workable long-term for SMC and AIM.

Some place in the README I suggest copying the two CSS files along with the main 
file.  I've had my students do that with little trouble.  Is there a better 
place to describe this?

You are a pilot site - for exactly this reason - we want to get all the kinks 
out.  ;-)  Thanks for reporting this promptly.  Also, thanks for making an issue 
(that's exactly the right place for this!).  I'm cc'ing the test-site list, just 
so everybody gets another heads-up.

Rob

**Comment by rbeezer** [comment]
@drewyoungren Should be all fixed.  You will need to pull and re-investigate any of the SMC worksheets, since they have all changed.  More on the "test-site" list.

Thanks again for reporting this.
